INSERT INTO catalog_areas (name) VALUES
  ('CV NOTICIAS'),
  ('FACULTAD DE EDUCACION'),
  ('FLOW'),
  ('MARKETING Y COMUNICACIONES'),
  ('AUTOMATIZACION'),
  ('OFICINA CV NOTICIAS'),
  ('ANALITICA DE DATOS'),
  ('SISTEMAS DE INFORMACION'),
  ('TESORERIA'),
  ('PRESUPUESTO'),
  ('INNOVACION EDUCATIVA')
ON CONFLICT (name) DO NOTHING;
